name: serenypals_frontend # Menggunakan nama dari pubspec pertama
description: "A new Flutter project."
publish_to: 'none' # Ensures your package isn't accidentally published to pub.dev
version: 0.1.0+1 # Menggunakan versi dari pubspec kedua

environment:
  # This constraint indicates compatibility with Dart SDK versions from 3.2.0 (inclusive)
  # up to, but not including, 4.0.0. This covers all current stable Dart 3.x versions.
  # (Recommended to run 'flutter upgrade' to ensure your Flutter/Dart SDK is recent)
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter # Required for any Flutter project

  # Dependencies from pubspec 1
  carousel_slider: ^5.0.0
  flutter_localizations: # Standard Flutter localization package
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  intl: 0.19.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  go_router: ^15.1.2
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  equatable: ^2.0.7
  provider: ^6.0.5

  # Dependencies from pubspec 2 (cupertino_icons)
  cupertino_icons: ^1.0.8 # Good to have for basic icons

dev_dependencies:
  flutter_test:
    sdk: flutter # For writing Flutter unit and widget tests
  integration_test: # From pubspec 1
    sdk: flutter
  flutter_lints: ^5.0.0 # Standard lints for Flutter projects. Compatible with Dart 3.5+
  mockito: ^5.4.6 # From pubspec 1
  bloc_test: ^10.0.0 # From pubspec 1
  build_runner: ^2.4.6 # From pubspec 1

flutter:
  uses-material-design: true

  # Fonts from pubspec 1
  fonts:
    - family: Overlock
      fonts:
        - asset: assets/fonts/Overlock-Regular.ttf
          weight: 400
        - asset: assets/fonts/Overlock-Bold.ttf
          weight: 700
        - asset: assets/fonts/Overlock-Black.ttf
          weight: 900
        - asset: assets/fonts/Overlock-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Overlock-BoldItalic.ttf
          weight: 700
          style: italic

  # Assets from both pubspecs (combined)
  assets:
    - assets/img/gambarlogin1.png
    - assets/img/gambarlogin2.png
    - assets/img/gambarlogin3.png
    - assets/img/onboarding1.png
    - assets/img/onboarding2.png
    - assets/img/onboarding3.png
    - assets/img/logo.png
    - assets/img/ai.png
    - assets/img/Dashboard.svg
    - assets/img/Diary.svg
    - assets/img/konsultasi.png
    - assets/img/konsultasifab.png
    - assets/img/premium.png
    - assets/img/sharingforum.svg
    - assets/img/close.svg
    - assets/img/Profile.svg
    - assets/img/chatadd.svg
    - assets/img/qris_dummy.png
    - assets/img/capybara1.png
    - assets/img/capybara2.png
    - assets/img/capybara3.png
    - assets/img/diamond.png
    - assets/img/moodjournaling.png
    - assets/loading/Capybaratea.gif
    - assets/images/bear_boba.png 
    - assets/capybara.png
