name: serenypals_frontend # Menggunakan nama dari pubspec tim
description: "A new Flutter project for SerenyPals." # Deskripsi baru
publish_to: 'none' # Memastikan paket tidak terpublish ke pub.dev
version: 0.1.0+1 # Menggunakan versi dari pubspec tim

environment:
  # Menggunakan batasan SDK yang lebih luas dan terkini dari pubspec tim
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter # Wajib untuk setiap proyek Flutter

  # Dependensi dari pubspec tim Anda
  carousel_slider: ^5.0.0
  flutter_localizations:
    sdk: flutter # Standar untuk lokalisasi Flutter
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  intl: ^0.19.0 # Pastikan versi ini kompatibel
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  go_router: ^15.1.2
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  equatable: ^2.0.7
  cupertino_icons: ^1.0.8 # Ikon Cupertino

  # Dependensi dari pubspec Anda (provider dan audioplayers)
  # Menggunakan versi provider yang lebih tinggi jika ada perbedaan
  provider: ^6.0.5 # Menggunakan versi ^6.0.5 dari pubspec tim Anda
  audioplayers: ^6.0.0 # Menggunakan versi ^6.0.0 (sama di kedua pubspec)

dev_dependencies:
  flutter_test:
    sdk: flutter # Untuk menulis unit dan widget tests Flutter
  integration_test:
    sdk: flutter # Dari pubspec tim Anda
  flutter_lints: ^5.0.0 # Lints standar untuk proyek Flutter
  mockito: ^5.4.6 # Dari pubspec tim Anda
  bloc_test: ^10.0.0 # Dari pubspec tim Anda
  build_runner: ^2.4.6 # Dari pubspec tim Anda

flutter:
  uses-material-design: true

  # Font dari pubspec tim Anda
  fonts:
    - family: Overlock
      fonts:
        - asset: assets/fonts/Overlock-Regular.ttf
          weight: 400
        - asset: assets/fonts/Overlock-Bold.ttf
          weight: 700
        - asset: assets/fonts/Overlock-Black.ttf
          weight: 900
        - asset: assets/fonts/Overlock-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Overlock-BoldItalic.ttf
          weight: 700
          style: italic

  # Aset dari kedua pubspec (digabungkan)
  assets:
    # Aset dari pubspec tim Anda (folder img, loading, images)
    - assets/img/gambarlogin1.png
    - assets/img/gambarlogin2.png
    - assets/img/gambarlogin3.png
    - assets/img/onboarding1.png
    - assets/img/onboarding2.png
    - assets/img/onboarding3.png
    - assets/img/logo.png
    - assets/img/ai.png
    - assets/img/Dashboard.svg
    - assets/img/Diary.svg
    - assets/img/konsultasi.png
    - assets/img/konsultasifab.png
    - assets/img/premium.png
    - assets/img/sharingforum.svg
    - assets/img/close.svg
    - assets/img/Profile.svg
    - assets/img/chatadd.svg
    - assets/img/qris_dummy.png
    - assets/img/diamond.png
    - assets/img/moodjournaling.png
    - assets/loading/Capybaratea.gif # GIF Capybara (sepertinya untuk loading)
    - assets/img/bear_boba.png
    - assets/img/capybara.png
    - assets/img/capybara1.png
    - assets/img/capybara3.png
    - assets/img/capybara2.png
    # Aset khusus Anda (gambar capybara_pet dan audio)
    - assets/img/capybara_pet.png # Gambar utama capybara Anda
    - assets/audio/background_music.mp3 